(() => {
'use strict';
const C=window.INCENTIFY_CONFIG,A=window.incentifyApi,Auth=window.IncentifyAuth;
const ARRAY_KEYS=['bills','invoices','customers','activityLog','expenses','earnings','balanceSheetEntries','paymentRequests','paymentTransactions','paymentSyncLog','paymentWebhookEvents','paymentAuditLogs'];
let sessionToken=Auth.token(),currentUser=null,committedState=null,committedRevision=0,pendingState=null,saving=false,pollTimer=null,cloudDataListeners=[],cloudStatusListeners=[];
const clone=v=>JSON.parse(JSON.stringify(v==null?null:v)); const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const stableKey=item=>{if(!item||typeof item!=='object')return null;const v=item.id||item.ID||item.customerId||item.CUSTOMER_ID||item.invoiceId||item.INVOICE_ID||item.expenseId||item.earningId||item.payment_request_id||item.paymentRequestId||item.razorpay_payment_id||item.razorpay_payment_link_id||item.reference_id||item.referenceId||item.number||item.invoice_number||item.transactionId||item.entryId||item.uuid||item._syncId;return v==null||v===''?null:String(v)};
const canPatchById=a=>Array.isArray(a)&&a.every(x=>x&&typeof x==='object'&&stableKey(x));
function diffCollection(a,b){if(!canPatchById(a)||!canPatchById(b))return{replace:clone(b||[])};const am=new Map(a.map(x=>[stableKey(x),x])),bm=new Map(b.map(x=>[stableKey(x),x])),upsert=[],deleteIds=[];for(const[k,x]of bm)if(!am.has(k)||!equal(am.get(k),x))upsert.push(clone(x));for(const k of am.keys())if(!bm.has(k))deleteIds.push(k);return{upsert,deleteIds}}
function buildPatch(a,b,rev){a=a||{};b=b||{};const p={baseRevision:Number(rev||0),scalars:{},collections:{},replace:{}};const keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys){if(ARRAY_KEYS.includes(k))continue;if(!equal(a[k],b[k]))p.scalars[k]=clone(b[k])}for(const k of ARRAY_KEYS){const x=Array.isArray(a[k])?a[k]:[],y=Array.isArray(b[k])?b[k]:[];if(equal(x,y))continue;const d=diffCollection(x,y);if('replace'in d)p.replace[k]=d.replace;else p.collections[k]=d}return p}
const hasChanges=p=>Object.keys(p.scalars).length||Object.keys(p.collections).length||Object.keys(p.replace).length;
function emitStatus(s){cloudStatusListeners.forEach(fn=>{try{fn(s)}catch(_){}})} function emitData(s,m){cloudDataListeners.forEach(fn=>{try{fn(clone(s),m||{})}catch(_){}})}
async function boot(){if(!sessionToken){location.replace('index.html');throw new Error('Authentication required');}try{const r=await A.call('bootstrap',{token:sessionToken});currentUser=r.user;committedState=clone(r.state);committedRevision=Number(r.revision||0);decorateUser();startPolling();return clone(committedState)}catch(e){Auth.clearSession();location.replace('index.html');throw e}}
function decorateUser(){document.querySelectorAll('.win-btn').forEach(x=>x.style.display='none');const right=document.querySelector('.tb-right');if(!right||document.getElementById('web-user-chip'))return;const chip=document.createElement('div');chip.id='web-user-chip';chip.style.cssText='display:flex;align-items:center;gap:7px;color:#dce9f5;font-size:10px;background:rgba(255,255,255,.08);padding:5px 9px;border-radius:7px';chip.innerHTML=`<span>${esc(currentUser?.name||currentUser?.email||'User')} · ${esc(currentUser?.role||'')}</span>${currentUser?.role==='ADMIN'?'<button id="web-admin-btn">Admin</button>':''}<button id="web-logout-btn">Logout</button>`;right.insertBefore(chip,right.firstChild);chip.querySelectorAll('button').forEach(b=>b.style.cssText='border:0;background:rgba(255,255,255,.12);color:#fff;border-radius:5px;padding:3px 7px;cursor:pointer;font:inherit');document.getElementById('web-admin-btn')?.addEventListener('click',()=>window.open('admin.html','_blank','noopener'));document.getElementById('web-logout-btn').onclick=()=>Auth.logout();}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function processSaves(){if(saving||!pendingState||!sessionToken)return;saving=true;emitStatus({mode:'CLOUD',syncing:true,revision:committedRevision});try{while(pendingState){const target=clone(pendingState);pendingState=null;const patch=buildPatch(committedState||{},target,committedRevision);if(!hasChanges(patch)){committedState=target;continue}const mutationId='web-'+Date.now()+'-'+Math.random().toString(36).slice(2);const r=await A.call('commitPatch',{token:sessionToken,mutationId,patch},60000);committedState=clone(r.state);committedRevision=Number(r.revision||committedRevision);if(!pendingState&&!equal(committedState,target))emitData(committedState,{source:'merge',revision:committedRevision})}emitStatus({mode:'CLOUD',syncing:false,revision:committedRevision,lastSync:new Date().toISOString()})}catch(e){emitStatus({mode:'ERROR',syncing:false,error:e.message,revision:committedRevision});console.error('Cloud save failed',e);if(['AUTH_REQUIRED','SESSION_EXPIRED','ACCESS_DENIED'].includes(e.code)){Auth.clearSession();location.replace('index.html')}}finally{saving=false;if(pendingState)setTimeout(processSaves,0)}}
function queueSave(state){if(currentUser?.role==='VIEWER')return Promise.resolve({success:false,reason:'read-only'});pendingState=clone(state);setTimeout(processSaves,20);return Promise.resolve({success:true,queued:true})}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(!sessionToken||saving||pendingState||document.hidden)return;try{const r=await A.call('poll',{token:sessionToken,sinceRevision:committedRevision});if(r?.changed){committedState=clone(r.state);committedRevision=Number(r.revision||0);emitData(committedState,{source:'poll',revision:committedRevision})}}catch(e){console.warn('Poll failed',e.message)}},C.POLL_MS)}
function downloadBase64(base64,mime,filename){const bin=atob(base64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);const url=URL.createObjectURL(new Blob([arr],{type:mime})),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function printElement(id,title){const node=document.getElementById(id);if(!node){window.print();return true}const w=window.open('','_blank');if(!w)return false;const styles=[...document.querySelectorAll('style,link[rel="stylesheet"]')].map(x=>x.outerHTML).join('');w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title>'+styles+'<style>@page{size:A4;margin:8mm}html,body{margin:0;background:#fff}body{padding:0}*{box-sizing:border-box}.no-print{display:none!important}</style></head><body>'+node.outerHTML+'<script>setTimeout(()=>window.print(),350)<\/script></body></html>');w.document.close();return true}
function receiptHtml(r={}){const b=r.business||{};return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:22mm}body{font-family:Arial;color:#182a3a}h1{color:#083866}.row{display:flex;justify-content:space-between;border-bottom:1px solid #e5ebf0;padding:9px 0}</style></head><body><h1>Payment Receipt</h1><strong>${esc(b.legalName||'INCENTIFY Private Limited')}</strong>${[['Receipt Number',r.receiptNumber],['Invoice Number',r.invoiceNumber],['Customer',r.customerName],['Payment Date',r.paymentDate],['Payment Method',r.paymentMethod],['Amount Received',r.amountReceived],['Payment ID',r.paymentId],['Remaining Balance',r.remainingBalance]].map(([a,c])=>`<div class="row"><span>${esc(a)}</span><strong>${esc(c||'')}</strong></div>`).join('')}</body></html>`}
function financeHtml(p={}){const s=p.settings||{},e=p.earnings||[],x=p.expenses||[],bs=p.balanceSheet||{};const te=e.reduce((a,b)=>a+Number(b.amount||0),0),tx=x.reduce((a,b)=>a+Number(b.amount||0),0);return `<!doctype html><html><head><meta charset="utf-8"><title>INCENTIFY Finance Report</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#182a3a}h1,h2{color:#083866}table{width:100%;border-collapse:collapse;margin-bottom:22px}td{padding:8px;border-bottom:1px solid #e5ebf0}td:last-child{text-align:right}</style></head><body><h1>${esc(s.legalName||'INCENTIFY Private Limited')}</h1><h2>Profit &amp; Loss</h2><table><tr><td>Earnings</td><td>₹${te.toFixed(2)}</td></tr><tr><td>Expenses</td><td>₹${tx.toFixed(2)}</td></tr><tr><td><strong>Net</strong></td><td><strong>₹${(te-tx).toFixed(2)}</strong></td></tr></table><h2>Balance Sheet</h2><table><tr><td>Total Assets</td><td>₹${Number(bs.totalAssets||0).toFixed(2)}</td></tr><tr><td>Total Liabilities</td><td>₹${Number(bs.totalLiabilities||0).toFixed(2)}</td></tr><tr><td>Total Equity</td><td>₹${Number(bs.totalEquity||0).toFixed(2)}</td></tr></table></body></html>`}
function printHtml(html,title){const w=window.open('','_blank');if(!w)return false;w.document.write(html);w.document.close();w.document.title=title;setTimeout(()=>w.print(),250);return true}
window.electronAPI={
 minimize:()=>{},maximize:()=>{},close:()=>{},loadData:boot,saveData:queueSave,
 exportPDF:async n=>({success:printElement('invoice-doc','Invoice '+(n||'')),path:'Browser print / Save as PDF'}),
 exportPaymentReceipt:async r=>({success:printHtml(receiptHtml(r),'INCENTIFY Payment Receipt'),path:'Browser print / Save as PDF'}),
 exportExcel:async payload=>{try{const r=await A.call('exportWorkbook',{token:sessionToken,payload},90000);downloadBase64(r.base64,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',r.filename||'INCENTIFY_Financial_Reports.xlsx');return{success:true,path:r.filename}}catch(e){return{success:false,reason:e.message}}},
 exportFinanceReport:async payload=>({success:printHtml(financeHtml(payload),'INCENTIFY Finance Report'),path:'Browser print / Save as PDF'}),checkNotifications:()=>{},
 loadGatewayConfig:()=>A.call('gatewayLoadConfig',{token:sessionToken}),saveGatewayConfig:config=>A.call('gatewaySaveConfig',{token:sessionToken,config}),autoConfigureGateway:()=>A.call('gatewayLoadConfig',{token:sessionToken}),
 gatewayRequest:async request=>{try{const r=await A.call('gatewayRequest',{token:sessionToken,request},90000);return{success:true,status:r.status||200,data:r.data}}catch(e){return{success:false,status:0,error:e.message,details:e.details||null}}},
 openExternal:async url=>{window.open(String(url),'_blank','noopener,noreferrer');return true},copyText:async text=>{await navigator.clipboard.writeText(String(text||''));return true},
 reserveInvoiceNumber:(prefix,year)=>A.call('reserveInvoiceNumber',{token:sessionToken,prefix,year}),
 cloudStatus:async()=>({mode:'CLOUD',activated:!!sessionToken,revision:committedRevision,user:currentUser}),cloudSyncNow:async()=>{const r=await A.call('poll',{token:sessionToken,sinceRevision:0});if(r?.state){committedState=clone(r.state);committedRevision=Number(r.revision||0);emitData(committedState,{source:'manual',revision:committedRevision})}return{success:true,revision:committedRevision}},openCloudActivation:async()=>({success:true,mode:'WEB_AUTH'}),createCloudBackup:()=>A.call('createBackup',{token:sessionToken}),createLocalBackup:async()=>({success:false,reason:'Web edition uses server backups.'}),
 onCloudDataUpdated:fn=>{if(typeof fn!=='function')return()=>{};cloudDataListeners.push(fn);return()=>cloudDataListeners=cloudDataListeners.filter(x=>x!==fn)},onCloudStatusUpdated:fn=>{if(typeof fn!=='function')return()=>{};cloudStatusListeners.push(fn);return()=>cloudStatusListeners=cloudStatusListeners.filter(x=>x!==fn)}
};
window.INCENTIFY_WEB={getUser:()=>currentUser,getRevision:()=>committedRevision,logout:()=>Auth.logout()};
})();
